name: booking_calendar
description: Flutter package to book online through your application. Use with
  streams to get real-time booking data, eg with Firestore streams
version: 1.3.2
homepage: https://github.com/radikris/booking_calendar

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  intl: ^0.19.0
  provider: ^6.0.5
  table_calendar: ^3.1.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
